### ISSUE TITLE
Wrong structure

### ISSUE THREAD

**Issue by AndreiSerov** [PyroBomber/BrownFox#1]
Wrog project structure. IDEA do all things instead of u. [Enjoy possibilities](https://kotlinlang.org/docs/tutorials/getting-started.html)

**Comment by ABashkirova** [comment]
Не было такого требования делать проект в IDEA

**Comment by AndreiSerov** [comment]
> Не было такого требования делать проект в IDEA

Рекомендация была =) Настоятельная!
