### ISSUE TITLE
лучше создать пустой список

### ISSUE THREAD

**Issue by kozlyakov-m** [PyroBomber/BrownFox#3]
`var words: MutableMap<String, Int?> = mutableMapOf()`
в цикле тогда начинать с 0

https://github.com/PyroBomber/BrownFox/blob/067977253beea548c1c58482a73c7c5759378bc7/lvl5.kt#L3

**Comment by PyroBomber** [comment]
В прошлый раз идея ругалась когда я так пытался сделать, теперь вроде получилось.
